# Configuración de la Base de Datos
spring.datasource.url=jdbc:mysql://localhost:3306/eldesborde_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuración de Cloudinary
cloudinary.cloud_name=dncx1tvna
cloudinary.api_key=127221499282315
cloudinary.api_secret=9Eeia69gaGCsVwfnZ4qeduZXrxI